repos:
- repo: local
  hooks:
    - id: cairo-formatter
      name: cairo-formatter
      entry: ./scripts/format-cairo-1.0-contracts.sh
      language: script
      pass_filenames: false
- repo: local
  hooks:
    - id: cairo-test
      name: cairo-test
      language: script
      entry: ./scripts/test-cairo-1.0-contracts.sh
      pass_filenames: false
- repo: local    
  hooks:
    - id: cairo-latest
      name: cairo-latest
      entry: ./scripts/install-cairo-1.0.sh
      language: script
      pass_filenames: false
