mod tests;

mod calls;
mod asserts;

mod argent_account;
use argent_account::ArgentAccount;

mod erc20;
use erc20::ERC20;

mod test_dapp;
use test_dapp::TestDapp;

// TODO Delete all under this when automatically generated by Framework
use argent_account::ArgentAccount::Escape;
use starknet::StorageAccess;
use serde::Serde;
use option::OptionTrait;
use traits::Into;
use traits::TryInto;
use integer::FeltTryIntoU64;

impl StorageAccessEscape of StorageAccess::<Escape> {
    fn read(
        address_domain: felt, base: starknet::StorageBaseAddress
    ) -> starknet::SyscallResult<Escape> {
        Result::Ok(
            Escape {
                active_at: (StorageAccess::read(address_domain, base)?),
                escape_type: starknet::storage_read_syscall(
                    address_domain, starknet::storage_address_from_base_and_offset(base, 1_u8)
                )?,
            }
        )
    }
    fn write(
        address_domain: felt, base: starknet::StorageBaseAddress, value: Escape
    ) -> starknet::SyscallResult<()> {
        StorageAccess::write(address_domain, base, value.active_at)?;
        starknet::storage_write_syscall(
            address_domain,
            starknet::storage_address_from_base_and_offset(base, 1_u8),
            value.escape_type
        )
    }
}

impl EscapeSerde of Serde::<Escape> {
    fn serialize(ref serialized: Array<felt>, input: Escape) {
        Serde::serialize(ref serialized, input.active_at);
        Serde::serialize(ref serialized, input.escape_type);
    }
    fn deserialize(ref serialized: Array<felt>) -> Option<Escape> {
        Option::Some(
            Escape {
                active_at: Serde::deserialize(ref serialized)?,
                escape_type: Serde::deserialize(ref serialized)?,
            }
        )
    }
}
